name-template: 'Draft 🌈'
prerelease: true
exclude-labels:
  - 'skip-changelog'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📖 Docs'
    labels:
      - 'docs'
  - title: '📦 Dependencies'
    labels:
      - 'dependencies'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- #$NUMBER: $TITLE'
template: |
  ## Changes
  $CHANGES
