- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "chore"
  color: "eeeeee"
  description: "Chore"
- name: "deps"
  color: "f9d0c4"
  description: "Dependencies"
- name: "docs"
  color: "0075ca"
  description: "Improvements or additions to documentation"
  from_name: "documentation"
- name: "feature"
  color: "a2eeef"
  description: "New feature or request"
  from_name: "enhancement"
- name: "fix"
  color: "d73a4a"
  description: "Bug fix"
- name: "skip-changelog"
  color: "eeeeee"
  description: "Don't include in Release Drafter"
