name: Push
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Run
        run: make run args="font-family"
