name: Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.8
      - run: deno --version

      - name: Install denon
        run: |
          deno --version
          deno install -qAf --unstable https://deno.land/x/denon/denon.ts
          denon --version

      - name: Run
        run: denon run font-family

      - name: Test
        run: denon test

      - name: Build
        run: denon make
