name: Push

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@main
        with:
          deno-version: "1.9.2"

      - run: deno --version

      - name: Install denon
      - run: |
          deno install -qAf --unstable https://deno.land/x/denon/denon.ts
          denon --version

      - name: Run
        run: denon run font-family

      # - name: Check
      #   run: denon check

      - name: Test
        run: denon test

      - name: Build
        run: denon make
