name: Sync labels

on:
  push:
    # NOTE: masterにマージかつpathsのファイルに変更があった場合のみ実行
    branches:
      - master
    paths:
      - '.github/sync-labels.yml'
      - '.github/workflows/sync-labels.yml'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-github-labeler@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: '.github/sync-labels.yml'
          skip-delete: false
          dry-run: false
